version: "3"
services:
  web:
    build:
      ./
    ports:
      - "8080:8080"
    environment:
      - REDIS_NAME=redis
      - APP_URL=http://localhost:8080
    depends_on:
      - redis

  redis:
    image: redis